### ISSUE TITLE
Movement on asteroids looks very janky.

### ISSUE THREAD

**Issue by UnderscoreX5** [paradoxReborn/SurvivalReborn-Spacewalk#2]
It's a while I don't play the game and I decided to come back. Saw this mod and decided to try it but I noticed that the movement while walking on asteroids is very shakey. If I recall correctly this behaviour isn't found in the vanilla.

**Comment by paradoxReborn** [comment]
Try it again with no mods - this is a vanilla issue. While I have made some improvements to movement, this particular issue is out of scope for Survival Reborn: Spacewalk.
