### ISSUE TITLE
Crash with non-human NPCs

### ISSUE THREAD

**Issue by itsDIETZ** [paradoxReborn/SurvivalReborn-Spacewalk#3]
Here are the logs of the last crash I had. 

[SpaceEngineers_20220818_12543294.log](https://github.com/paradoxReborn/SurvivalReborn-Spacewalk/files/9384335/SpaceEngineers_20220818_12543294.log)

**Comment by paradoxReborn** [comment]
Reproduced crash by enabling wolves with only Survival Reborn: Spacewalk and no other mods. A patch is in the works.

**Comment by paradoxReborn** [comment]
A possible fix has been released with Beta version 0.7 of the mod. Please comment here if you see wolves, spiders, etc. without crashing the game. If you have the same or a similar crash, please upload the log.

**Comment by paradoxReborn** [comment]
This issue appears to be fixed as of the latest version.
